config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users
  resources :drivers
  
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
# frozen_string_literal: true

class Driver < ApplicationRecord
  attribute :status, :boolean, default: true
  validates :name, :email, :phone_number, :address, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # validates :name, presence: true, allow_blank: false, on: :update, message: 'algo'
  validates_presence_of :name, on: :update, message: 'algo'
  validates :name,
            presence: { message: 'Por favor llena este campo con tu nombre completo' },
            on: :update

  validates :business_name,
            presence: { message: 'Por favor llena este campo con el nombre de tu negocio' },
            on: :update

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for(*)
    users_path(current_user.id)
  end
end

app/controllers/drivers_controller.rb
# frozen_string_literal: true

class DriversController < ApplicationController
  before_action :set_driver, only: %i[show destroy edit update]

  def index
    @drivers = Driver.all
  end

  def show; end

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)

    if @driver.save
      flash[:success] = 'Conductor creado con exito!'
      redirect_to @driver
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @driver.update_attributes(driver_params)
      flash[:success] = "El conductor #{@driver.name} ha sido actualizado"
      redirect_to @driver
    else
      render 'edit'
    end
  end

  def destroy
    flash[:success] = driver_destroyed if @driver.destroy
    redirect_to drivers_path
  end

  private

  def driver_destroyed
    "El conductor #{@driver.name} ha sido eliminado con exito"
  end

  def set_driver
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit(:name,
                                   :email,
                                   :phone_number,
                                   :address,
                                   :observations,
                                   :status)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(*)
    edit_user_path(current_user.id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Perfil actualizado'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :business_name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/drivers_helper.rb
# frozen_string_literal: true

module DriversHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/drivers/_form.html.haml
= form_for @driver do |d|
  %form
    .form-group
      = d.label :nombre, class: 'form-check-label'
      = d.text_field :name, class: 'form-control'
    .form-group
      = d.label :email, class: 'form-check-label'
      = d.text_field :email, class: 'form-control'
    .form-group
      = d.label :phone_number, class: 'form-check-label'
      = d.text_field :phone_number, class: 'form-control'
    .form-group
      = d.label :dirección, class: 'form-check-label'
      = d.text_field :address, class: 'form-control'
    .form-group
      = d.label :observaciones, class: 'form-check-label'
      = d.text_area :observations, class: 'form-control', rows: '5'

    = d.submit 'Aceptar', class: 'btn btn-primary btn-block'

app/views/drivers/edit.html.haml
.row
  %h1
    = "Estás editando al chofer: #{@driver.name}"

.row
  .col-md-6.offset-md-3
    = render "form"

app/views/drivers/index.html.haml
.row
  .col-md-12
    %h1
      Lista de choferes

.row
  .col-md-12
    %table.table.table-sm.table-striped
      %thead
        %tr
          %th
            Nombre
          %th
            Telefono
          %th
            Ver
          %th
            Editar
          %th
            Inhabilitar
      %tbody
      - @drivers.each do |d|
        %tr
          %td
            = d.name
          %td
            = d.phone_number
          %td
            = link_to('Ver', driver_path(d))
          %td
            = link_to('Editar', edit_driver_path(d))
          %td
            = link_to('Eliminar', driver_path(d), method: :delete, data: {confirm: "Etás seguro de eliminar a #{d.name}?"})

app/views/drivers/new.html.haml
%h1
  Agregar un conductor nuevo

.row
  .col-md-6.offset-md-3
    = render "form"

app/views/drivers/show.html.haml
.row.mt-5
  .col-md-4
    .text-center
      %img.img-thumbnail.rounded{src: 'https://st2.depositphotos.com/1104517/11967/v/950/depositphotos_119675554-stock-illustration-male-avatar-profile-picture-vector.jpg', alt:'@driver.name'}

  .col-md-6
    .card{style:'width 18rem;'}
      .card-body
        %h5.card-title
          = @driver.name
        %p.card-text
          = @driver.email
        %p.card-text
          = @driver.phone_number
        %p.card-text
          = @driver.observations
        %p.card-text
          = @driver.status

  .col-md-2
    .text-left.mb-3
      = link_to 'Imprimir perfil', '#', class: 'btn btn-primary btn-block'
    .text-left.mb-3
      = link_to 'Imprimir historial', '#', class: 'btn btn-primary btn-block'
    .text-left.mb-3
      = link_to 'Ediar perfil', edit_driver_path(@driver), class: 'btn btn-primary btn-block'
    .text-left.mb-3
      = link_to 'Inhabilitar chofer', '#', class: 'btn btn-danger btn-block'

app/views/home/index.html.haml
= link_to 'Registrate', new_user_registration_path
= link_to 'Inicia sesión', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yotellevo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= render "layouts/partials/alerts" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/users/_form.html.haml
- if @user.errors.any?
  %div
    %h2
      = pluralize(@user.errors.count, "error")
      prohibited this logo from being saved:
    %ul
      - @user.errors.full_messages.each do |msg|
        %li.alert.alert-warning= msg

= form_for @user do |u|
  %form
    .form-group
      = u.label :nombre, class: 'form-check-label'
      = u.text_field :name, class: 'form-control'
    .form-group
      = u.label :business_name, class: 'form-check-label'
      = u.text_field :business_name, class: 'form-control'

    = u.submit 'Aceptar', class: 'btn btn-primary btn-block'

app/views/users/edit.html.haml
.row
  %h1
    = "Estás editando al Usuario: #{@user.name}"

.row
  .col-md-6.offset-md-3
    = render "form"

app/views/users/index.html.haml
- if user_signed_in?
  =link_to 'Cerrar sesión', destroy_user_session_path, method: :delete
- else

%h1 Users list
= @users.count

app/views/users/show.html.haml
%h1 Show users
= @user.name